language: 
  - java

jdk:
  - oraclejdk8

install:
  - mvn clean package

after_success:
  - mvn clean cobertura:cobertura-integration-test coveralls:report -DrepoToken="$COVERALLS_TOKEN"

cache:
  directories:
    - $HOME/.m2 